"""ROS 2 demo node for interactively commanding RH1 foot-plate orientation."""

import os

import rclpy
from ament_index_python.packages import get_package_share_directory
from rclpy.node import Node
from sensor_msgs.msg import JointState

from rh1.ankle_rehab_control import (
    ALL_DEMO_JOINTS,
    default_joint_limits,
    passive_targets_from_actuated,
    position_tick_from_rad,
)
from rh1.parallel_ik import (
    NoIKSolution,
    ParallelAnkleIK,
    deg_to_rad,
    load_params_json,
    rad_to_deg,
)


class ParallelIKPoseDemo(Node):
    def __init__(self):
        super().__init__("parallel_ik_pose_demo")

        package_share = get_package_share_directory("rh1")
        default_params = os.path.join(
            package_share, "config", "parallel_ik_autogenerated.json"
        )

        self.declare_parameter("ik_params_path", default_params)
        self.declare_parameter("pitch_deg", 0.0)
        self.declare_parameter("roll_deg", 0.0)
        self.declare_parameter("yaw_deg", 0.0)
        self.declare_parameter("publish_rate_hz", 30.0)
        self.declare_parameter("tolerance_mm", 1.0)
        self.declare_parameter("samples", 181)
        self.declare_parameter("log_period_s", 1.0)

        self.ik_params_path = self.get_parameter("ik_params_path").value
        self.publish_rate_hz = float(self.get_parameter("publish_rate_hz").value)
        self.log_period_s = float(self.get_parameter("log_period_s").value)
        self.last_log_time = self.get_clock().now()
        self.last_solution = {}
        self.publisher = self.create_publisher(JointState, "joint_states", 10)
        self.passive_limits = default_joint_limits()

        params = load_params_json(self.ik_params_path)
        self.ik = ParallelAnkleIK(params)

        self.timer = self.create_timer(1.0 / self.publish_rate_hz, self._on_timer)

        self.get_logger().warn(
            "Using IK params: %s. Autogenerated params are for visualization/software bring-up only."
            % self.ik_params_path
        )
        self.get_logger().info(
            "Change pose live with: ros2 param set /parallel_ik_pose_demo pitch_deg 5.0"
        )

    def _on_timer(self):
        pitch_deg = float(self.get_parameter("pitch_deg").value)
        roll_deg = float(self.get_parameter("roll_deg").value)
        yaw_deg = float(self.get_parameter("yaw_deg").value)
        tolerance_mm = float(self.get_parameter("tolerance_mm").value)
        samples = int(self.get_parameter("samples").value)

        try:
            result = self.ik.solve_orientation(
                roll_rad=deg_to_rad(roll_deg),
                pitch_rad=deg_to_rad(pitch_deg),
                yaw_rad=deg_to_rad(yaw_deg),
                previous_solution=self.last_solution,
                samples=samples,
                tolerance_mm=tolerance_mm,
            )
        except NoIKSolution as exc:
            self.get_logger().warn("IK failed: %s" % exc)
            return

        active_positions = result["joint_angles_rad"]
        self.last_solution = active_positions
        passive_positions = passive_targets_from_actuated(
            active_positions,
            self.passive_limits,
        )
        positions = {}
        positions.update(active_positions)
        positions.update(passive_positions)

        msg = JointState()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.name = list(ALL_DEMO_JOINTS)
        msg.position = [positions.get(name, 0.0) for name in msg.name]
        msg.velocity = []
        msg.effort = []
        self.publisher.publish(msg)

        self._log_solution_if_due(pitch_deg, roll_deg, yaw_deg, result)

    def _log_solution_if_due(self, pitch_deg, roll_deg, yaw_deg, result):
        now = self.get_clock().now()
        elapsed = (now - self.last_log_time).nanoseconds * 1e-9
        if elapsed < self.log_period_s:
            return
        self.last_log_time = now

        joint_angles = result["joint_angles_rad"]
        residuals = result["residuals_mm"]
        fields = []
        for joint_name in ("joint1", "joint4", "joint6"):
            angle_rad = joint_angles[joint_name]
            fields.append(
                "%s=%.2f deg tick=%d residual=%.3f mm"
                % (
                    joint_name,
                    rad_to_deg(angle_rad),
                    position_tick_from_rad(angle_rad),
                    residuals[joint_name],
                )
            )

        self.get_logger().info(
            "foot pitch=%.2f roll=%.2f yaw=%.2f deg -> %s"
            % (pitch_deg, roll_deg, yaw_deg, "; ".join(fields))
        )


def main(args=None):
    rclpy.init(args=args)
    node = ParallelIKPoseDemo()
    try:
        rclpy.spin(node)
    finally:
        if rclpy.ok():
            node.destroy_node()


if __name__ == "__main__":
    main()
