#!/usr/bin/env python3
"""Generate a complete first-pass RH1 parallel IK parameter file.

This is a best-effort bootstrapper. It selects three strong actuator-axis
candidates from the STEP extraction report, then constructs a conservative
geometric first-pass model that can exercise the IK solver. Use it for software
bring-up, not for direct full-range hardware motion without validation.
"""

import argparse
import json
import math
import os


JOINT_NAMES = ("joint1", "joint4", "joint6")


def dot(left, right):
    return sum(a * b for a, b in zip(left, right))


def cross(left, right):
    return (
        left[1] * right[2] - left[2] * right[1],
        left[2] * right[0] - left[0] * right[2],
        left[0] * right[1] - left[1] * right[0],
    )


def add(left, right):
    return [a + b for a, b in zip(left, right)]


def sub(left, right):
    return [a - b for a, b in zip(left, right)]


def scale(vector, factor):
    return [component * factor for component in vector]


def norm(vector):
    return math.sqrt(dot(vector, vector))


def normalize(vector):
    length = norm(vector)
    if length == 0.0:
        raise ValueError("Cannot normalize a zero-length vector.")
    return [component / length for component in vector]


def distance(left, right):
    return norm(sub(left, right))


def rounded(values, digits=6):
    return [round(value, digits) for value in values]


def centroid(points):
    return [
        sum(point[index] for point in points) / float(len(points))
        for index in range(3)
    ]


def point_magnitude(point):
    return norm(point)


def choose_actuator_axes(candidates):
    strong = [
        candidate
        for candidate in candidates
        if 8.0 <= candidate["radius_mm"] <= 12.0
        and candidate["count"] >= 3
        and point_magnitude(candidate["point_mm"]) < 200.0
    ]
    strong.sort(key=lambda item: (-item["count"], point_magnitude(item["point_mm"])))
    if len(strong) < 3:
        raise RuntimeError("Could not find three strong actuator-axis candidates.")

    selected = strong[:3]
    selected.sort(key=lambda item: math.atan2(item["point_mm"][1], item["point_mm"][0]))
    return selected


def perpendicular_direction(axis_direction, radial_hint):
    axis = normalize(axis_direction)
    radial = sub(radial_hint, scale(axis, dot(radial_hint, axis)))
    if norm(radial) < 1e-6:
        radial = cross(axis, [0.0, 0.0, 1.0])
    if norm(radial) < 1e-6:
        radial = cross(axis, [0.0, 1.0, 0.0])
    return normalize(radial)


def auto_generate_params(report, horn_radius_mm, foot_radius_mm, motor_limit_deg):
    axes = choose_actuator_axes(report["candidate_axis_clusters"])
    axis_points = [axis["point_mm"] for axis in axes]
    ankle_center = centroid(axis_points)

    legs = []
    for joint_name, axis in zip(JOINT_NAMES, axes):
        axis_point = axis["point_mm"]
        axis_direction = normalize(axis["direction"])
        radial_from_center = normalize(sub(axis_point, ankle_center))
        horn_direction = perpendicular_direction(axis_direction, radial_from_center)

        horn_point = add(axis_point, scale(horn_direction, horn_radius_mm))
        foot_point_base = add(ankle_center, scale(radial_from_center, foot_radius_mm))
        foot_point_foot = sub(foot_point_base, ankle_center)
        rod_length = distance(horn_point, foot_point_base)

        legs.append(
            {
                "name": joint_name,
                "dynamixel_id": len(legs) + 1,
                "source_cluster_id": axis["cluster_id"],
                "axis_point_base_mm": rounded(axis_point),
                "axis_direction_base": rounded(axis_direction),
                "horn_point_zero_base_mm": rounded(horn_point),
                "foot_point_foot_mm": rounded(foot_point_foot),
                "rod_length_mm": round(rod_length, 6),
                "zero_angle_rad": 0.0,
                "lower_angle_deg": -motor_limit_deg,
                "upper_angle_deg": motor_limit_deg,
            }
        )

    return {
        "units": "millimeter",
        "status": "autogenerated_unverified_geometry_for_software_bringup",
        "source_report": report.get("source_step", ""),
        "warnings": [
            "This file is fully automatic and unverified.",
            "It is suitable for exercising the IK solver and planning calibration.",
            "Do not use for full-range hardware control until the selected axes and connection points are confirmed.",
        ],
        "generation_assumptions": {
            "horn_radius_mm": horn_radius_mm,
            "foot_radius_mm": foot_radius_mm,
            "motor_limit_deg": motor_limit_deg,
            "actuator_axis_selection": "radius 8-12 mm, count >= 3, coordinates near the assembly origin",
            "horn_point_zero": "axis point plus a perpendicular horn-radius offset",
            "foot_point_foot": "radial point around the estimated ankle center",
        },
        "ankle_center_base_mm": rounded(ankle_center),
        "legs": legs,
    }


def parse_args():
    parser = argparse.ArgumentParser(description="Auto-generate first-pass IK parameters.")
    parser.add_argument(
        "--candidate-json",
        default=os.path.join("demo_output", "step_kinematics_candidates.json"),
        help="Path to STEP candidate JSON generated by extract_step_kinematics.py.",
    )
    parser.add_argument(
        "--output-json",
        default=os.path.join("params", "parallel_ik_params.autogenerated.json"),
        help="Output IK parameter JSON.",
    )
    parser.add_argument("--horn-radius-mm", type=float, default=20.0)
    parser.add_argument("--foot-radius-mm", type=float, default=60.0)
    parser.add_argument("--motor-limit-deg", type=float, default=90.0)
    return parser.parse_args()


def main():
    args = parse_args()
    with open(args.candidate_json, "r", encoding="utf-8") as report_file:
        report = json.load(report_file)

    params = auto_generate_params(
        report,
        horn_radius_mm=args.horn_radius_mm,
        foot_radius_mm=args.foot_radius_mm,
        motor_limit_deg=args.motor_limit_deg,
    )

    with open(args.output_json, "w", encoding="utf-8") as output_file:
        json.dump(params, output_file, indent=2)
        output_file.write("\n")

    print("Wrote:", os.path.abspath(args.output_json))
    print("Ankle center:", params["ankle_center_base_mm"])
    for leg in params["legs"]:
        print(
            "{name}: cluster {source_cluster_id}, rod_length {rod_length_mm:.3f} mm".format(
                **leg
            )
        )


if __name__ == "__main__":
    main()
