from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import Command, LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from launch.substitutions import FindExecutable


def generate_launch_description():
    package_name = "rh1"
    package_share = FindPackageShare(package=package_name)

    urdf_file = LaunchConfiguration("urdf_file")
    rviz_config_file = LaunchConfiguration("rviz_config_file")
    ik_params_path = LaunchConfiguration("ik_params_path")
    pitch_deg = LaunchConfiguration("pitch_deg")
    roll_deg = LaunchConfiguration("roll_deg")
    yaw_deg = LaunchConfiguration("yaw_deg")
    publish_rate_hz = LaunchConfiguration("publish_rate_hz")
    tolerance_mm = LaunchConfiguration("tolerance_mm")

    default_urdf = PathJoinSubstitution(
        [package_share, "urdf", "rh1_sim.urdf.xacro"]
    )
    default_rviz = PathJoinSubstitution(
        [package_share, "rviz", "ankle_rehab_demo.rviz"]
    )
    default_ik_params = PathJoinSubstitution(
        [package_share, "config", "parallel_ik_autogenerated.json"]
    )

    robot_description = {
        "robot_description": Command([FindExecutable(name="xacro"), " ", urdf_file])
    }

    return LaunchDescription(
        [
            DeclareLaunchArgument(
                "urdf_file",
                default_value=default_urdf,
                description="Simulation Xacro/URDF used by robot_state_publisher.",
            ),
            DeclareLaunchArgument(
                "rviz_config_file",
                default_value=default_rviz,
                description="RViz config for the IK pose demo.",
            ),
            DeclareLaunchArgument(
                "ik_params_path",
                default_value=default_ik_params,
                description="JSON parameter file for the parallel IK solver.",
            ),
            DeclareLaunchArgument(
                "pitch_deg",
                default_value="0.0",
                description="Foot plate pitch command in degrees.",
            ),
            DeclareLaunchArgument(
                "roll_deg",
                default_value="0.0",
                description="Foot plate roll command in degrees.",
            ),
            DeclareLaunchArgument(
                "yaw_deg",
                default_value="0.0",
                description="Foot plate yaw command in degrees.",
            ),
            DeclareLaunchArgument(
                "publish_rate_hz",
                default_value="30.0",
                description="JointState publish rate.",
            ),
            DeclareLaunchArgument(
                "tolerance_mm",
                default_value="1.0",
                description="IK residual tolerance for autogenerated geometry.",
            ),
            Node(
                package="robot_state_publisher",
                executable="robot_state_publisher",
                name="robot_state_publisher",
                output="screen",
                parameters=[robot_description],
            ),
            Node(
                package=package_name,
                executable="parallel_ik_pose_demo",
                name="parallel_ik_pose_demo",
                output="screen",
                parameters=[
                    {
                        "ik_params_path": ik_params_path,
                        "pitch_deg": pitch_deg,
                        "roll_deg": roll_deg,
                        "yaw_deg": yaw_deg,
                        "publish_rate_hz": publish_rate_hz,
                        "tolerance_mm": tolerance_mm,
                    }
                ],
            ),
            Node(
                package="rviz2",
                executable="rviz2",
                name="rviz2_parallel_ik_pose_demo",
                output="screen",
                arguments=["-d", rviz_config_file],
            ),
        ]
    )
